-- Call-type rules regenerated from the MCFRS Response Plans (section 1) merged with sta03's observed codes.
-- Upserts every default so existing branches pick up new codes and regraded severities; admin edits to
-- codes not in this list are untouched.
-- @@
INSERT INTO call_type_rules (code, description, category, severity, alertable, is_upgrade) VALUES
  ('2ND','Second alarm','fire','critical',true,true),
  ('3RD','Third alarm','fire','critical',true,true),
  ('4TH','Fourth alarm','fire','critical',true,true),
  ('AIRCRSHF','Aircraft crash with fire','fire','critical',true,false),
  ('AIRCRSHFW','Aircraft crash with fire, water','fire','critical',true,false),
  ('AIRFIREL','Aircraft fire, large','fire','critical',true,false),
  ('AIRFULLE','Aircraft emergency, full assignment','fire','critical',true,false),
  ('BLDGFIRE','Building fire','fire','critical',true,false),
  ('BLDGFIRET','Building fire, occupants trapped','fire','critical',true,false),
  ('BLDGFREX','Building fire with explosion','fire','critical',true,false),
  ('BLDGFREXH','Building fire with explosion, hazmat','fire','critical',true,false),
  ('BLDGFRH','Building fire, hazmat','fire','critical',true,false),
  ('BLDGFRHM','Building fire, hazmat','fire','critical',true,false),
  ('BLDGFRHMT','Building fire, hazmat, occupants trapped','fire','critical',true,false),
  ('BLDGFRHR','High-rise building fire','fire','critical',true,false),
  ('BLDGFRHRT','High-rise building fire, occupants trapped','fire','critical',true,false),
  ('BLDGFRSMT','Building fire, smoke showing, occupants trapped','fire','critical',true,false),
  ('BUILDING','Building fire','fire','critical',true,false),
  ('HOUSE','House fire','fire','critical',true,false),
  ('HOUSET','House fire, occupants trapped','fire','critical',true,false),
  ('MAFULL','Mutual aid full assignment','fire','critical',true,true),
  ('UBOX','Box alarm upgrade (working fire)','fire','critical',true,true),
  ('UBOXHR','High-rise box upgrade','fire','critical',true,true),
  ('UBOXW','Box upgrade, working fire','fire','critical',true,true),
  ('VEHFRBLH','Vehicle fire near building, hazmat','fire','critical',true,false),
  ('VEHFRTRAP','Vehicle fire with entrapment','fire','critical',true,false),
  ('AIRFIRES','Aircraft fire, small','fire','high',true,false),
  ('APLNCM','Appliance fire, multiple patients','fire','high',true,false),
  ('BLDGFIRS','Building fire, small','fire','high',true,false),
  ('BLDGFIRSM','Building fire, small, multiple patients','fire','high',true,false),
  ('BLDGFRSME','Building fire, smoke, electrical','fire','high',true,false),
  ('BOATFIREM','Boat fire, multiple patients','fire','high',true,false),
  ('BOATFROUM','Boat fire out, multiple patients','fire','high',true,false),
  ('BRUSHLG','Brush fire, large','fire','high',true,false),
  ('BRUSHLGB','Brush fire, large, BLS','fire','high',true,false),
  ('BRUSHLGM','Brush fire, large, multiple patients','fire','high',true,false),
  ('CHIMNEY','Chimney fire','fire','high',true,false),
  ('CHIMNEYS','Chimney fire, small','fire','high',true,false),
  ('DECKOVER','Vehicle fire under deck-over','fire','high',true,false),
  ('DECKOVH','Vehicle fire under deck-over, hazmat','fire','high',true,false),
  ('OUTFIREM','Outside fire, multiple patients','fire','high',true,false),
  ('VEHFIREM','Vehicle fire, multiple patients','fire','high',true,false),
  ('VEHFIRPRK','Vehicle fire in parking garage','fire','high',true,false),
  ('VEHFRBLDB','Vehicle fire near building, BLS','fire','high',true,false),
  ('VEHFRTRH','Vehicle fire, tractor-trailer, hazmat','fire','high',true,false),
  ('VFIRPRKH','Vehicle fire in parking garage, hazmat','fire','high',true,false),
  ('APLNCADA','Appliance fire, adaptive','fire','normal',false,false),
  ('APLNCADAB','Appliance fire, adaptive, BLS','fire','normal',false,false),
  ('APLNCB','Appliance fire, BLS','fire','normal',false,false),
  ('APLNCH','Appliance fire, hazmat','fire','normal',false,false),
  ('APLNCSE','Appliance fire, single engine','fire','normal',false,false),
  ('APPLIANCE','Appliance fire','fire','normal',false,false),
  ('AUTO','Vehicle incident','fire','normal',false,false),
  ('BOATFIRE','Boat fire','fire','normal',false,false),
  ('BOATFIREB','Boat fire, BLS','fire','normal',false,false),
  ('BOATFROUB','Boat fire out, BLS','fire','normal',false,false),
  ('BOATFROUT','Boat fire out','fire','normal',false,false),
  ('BOGS','Bog fire','fire','normal',false,false),
  ('BOGSB','Bog fire, BLS','fire','normal',false,false),
  ('BOGSM','Bog fire, multiple patients','fire','normal',false,false),
  ('BRUSHS','Brush fire, small','fire','normal',false,false),
  ('BRUSHSMB','Brush fire, small, BLS','fire','normal',false,false),
  ('BRUSHSMI','Brush fire, small, inside','fire','normal',false,false),
  ('BRUSHSMM','Brush fire, small, multiple patients','fire','normal',false,false),
  ('BTFIREWTR','Boat fire on the water','fire','normal',false,false),
  ('FIREOUT','Fire out','fire','normal',false,false),
  ('FIREOUTH','Fire out, hazmat','fire','normal',false,false),
  ('ODORSMK','Odor of smoke','fire','normal',false,false),
  ('OUTFIRE','Outside fire','fire','normal',false,false),
  ('OUTFIREB','Outside fire, BLS','fire','normal',false,false),
  ('OUTFRADA','Outside fire, adaptive','fire','normal',false,false),
  ('OUTFRADAB','Outside fire, adaptive, BLS','fire','normal',false,false),
  ('VEHEXP','Vehicle explosion','fire','normal',false,false),
  ('VEHEXPH','Vehicle explosion, hazmat','fire','normal',false,false),
  ('VEHFIRE','Vehicle fire','fire','normal',false,false),
  ('VEHFIREB','Vehicle fire, BLS','fire','normal',false,false),
  ('VEHFIRH','Vehicle fire, hazmat','fire','normal',false,false),
  ('VEHFIRLG','Vehicle fire, large','fire','normal',false,false),
  ('VEHFIRLGB','Vehicle fire, large, BLS','fire','normal',false,false),
  ('VEHFRBLDG','Vehicle fire near building','fire','normal',false,false),
  ('VEHFREXP','Vehicle fire with explosion','fire','normal',false,false),
  ('VEHFRLGH','Vehicle fire, large, hazmat','fire','normal',false,false),
  ('APLNCSER','Appliance fire, single engine, routine','fire','low',false,false),
  ('OUTFIRER','Outside fire, routine','fire','low',false,false),
  ('AIRCRSHP','Aircraft crash','rescue','critical',true,false),
  ('AIRCRSHPW','Aircraft crash in water','rescue','critical',true,false),
  ('DSASTRTRP','Disaster, people trapped','rescue','critical',true,false),
  ('ENTRAP1','Entrapment, ALS1','rescue','critical',true,false),
  ('ENTRAP2','Entrapment, ALS2','rescue','critical',true,false),
  ('ENTRAPHM1','Entrapment with hazmat, ALS1','rescue','critical',true,false),
  ('ENTRAPHM2','Entrapment with hazmat, ALS2','rescue','critical',true,false),
  ('FLDVEHT','Vehicle in flood water, occupants trapped','rescue','critical',true,false),
  ('METCRSH','Metro crash','rescue','critical',true,false),
  ('METRO','Metro rail incident','rescue','critical',true,false),
  ('METRORESQP','Metro rescue, person','rescue','critical',true,false),
  ('PIC1TRAP','Collision with entrapment','rescue','critical',true,false),
  ('PICMULT1','Multi-vehicle collision, ALS1','rescue','critical',true,false),
  ('PICMULT2','Multi-vehicle collision, ALS2','rescue','critical',true,false),
  ('PICTRAP1','Collision with entrapment, ALS1','rescue','critical',true,false),
  ('PICTRAP2','Collision with entrapment, ALS2','rescue','critical',true,false),
  ('PICTRAPF2','Collision with entrapment and fire, ALS2','rescue','critical',true,false),
  ('PICTRFHM2','Collision, entrapment, fire and hazmat, ALS2','rescue','critical',true,false),
  ('PICTRFM2','Collision with entrapment and fire, ALS2','rescue','critical',true,false),
  ('PICTRPHM1','Collision with entrapment, hazmat, ALS1','rescue','critical',true,false),
  ('PICTRPHM2','Collision with entrapment, hazmat, ALS2','rescue','critical',true,false),
  ('TRAINCRSH','Train crash','rescue','critical',true,false),
  ('TRAINFIRE','Train fire','rescue','critical',true,false),
  ('TRAINPED','Train vs pedestrian','rescue','critical',true,false),
  ('TRTCOLAPS','Structural collapse','rescue','critical',true,false),
  ('TRTCOLAPW','Collapse with water rescue','rescue','critical',true,false),
  ('TRTCONFIN','Confined space rescue','rescue','critical',true,false),
  ('TRTTECH','Technical rescue','rescue','critical',true,false),
  ('TRTTECHW','Technical rescue with water resources','rescue','critical',true,false),
  ('TRTTRENCH','Trench rescue','rescue','critical',true,false),
  ('DSASTRDAN','Disaster, danger','rescue','high',true,false),
  ('ELEVTRTRP','Elevator entrapment with injury','rescue','high',true,false),
  ('PIC2','Collision with injuries, ALS2','rescue','high',true,false),
  ('PICEXB','Collision, extrication needed, BLS','rescue','high',true,false),
  ('PICHM2','Collision with hazmat, ALS2','rescue','high',true,false),
  ('AIRALERT','Aircraft alert','rescue','normal',false,false),
  ('AIRMINRE','Aircraft minor emergency','rescue','normal',false,false),
  ('PIC1','Collision with injuries, ALS1','rescue','normal',false,false),
  ('PICB','Collision with injuries, BLS','rescue','normal',false,false),
  ('PICHM1','Collision with hazmat, ALS1','rescue','normal',false,false),
  ('PICHMB','Collision with hazmat, BLS','rescue','normal',false,false),
  ('TRAININV','Train investigation','rescue','normal',false,false),
  ('TRAININVR','Train investigation (routine)','rescue','normal',false,false),
  ('LOSTPERR','Lost person (routine)','rescue','low',false,false),
  ('ALLERGIC2','Allergic reaction, ALS2','ems','critical',true,false),
  ('BURNADA2','Burns, ALS2 with fire response','ems','critical',true,false),
  ('BURNMPD2','Burns, multiple patients','ems','critical',true,false),
  ('CHOKING2','Choking, ALS2','ems','critical',true,false),
  ('CPR2','Cardiac arrest','ems','critical',true,false),
  ('CPRDROWN2','Cardiac arrest, drowning','ems','critical',true,false),
  ('CPRHEMM2','Cardiac arrest, hemorrhage','ems','critical',true,false),
  ('CPRHM2','Cardiac arrest, hazmat','ems','critical',true,false),
  ('CPROD2','Cardiac arrest, overdose','ems','critical',true,false),
  ('CPRSHOT2','Cardiac arrest, gunshot','ems','critical',true,false),
  ('CPRSTAB2','Cardiac arrest, stabbing','ems','critical',true,false),
  ('CPRTRAUM2','Cardiac arrest, trauma','ems','critical',true,false),
  ('DROWN2','Drowning, ALS2','ems','critical',true,false),
  ('DSASTRMCI','Disaster, mass casualty','ems','critical',true,false),
  ('ELECTRO2','Electrocution, ALS2','ems','critical',true,false),
  ('ELECTROM','Electrocution, multiple patients','ems','critical',true,false),
  ('HEMM2','Hemorrhage, ALS2','ems','critical',true,false),
  ('SHOOTA2','Shooting, ALS2','ems','critical',true,false),
  ('SHOTPOL2','Shooting, police on scene, ALS2','ems','critical',true,false),
  ('SHOTPOLM','Shooting, police on scene, multiple patients','ems','critical',true,false),
  ('STAB2','Stabbing, ALS2','ems','critical',true,false),
  ('STABPOL2','Stabbing, police on scene, ALS2','ems','critical',true,false),
  ('STABPOLM','Stabbing, police on scene, multiple patients','ems','critical',true,false),
  ('TRAUMPOL2','Trauma, police on scene, ALS2','ems','critical',true,false),
  ('TRAUMPOLM','Trauma, police on scene, multiple patients','ems','critical',true,false),
  ('UCODE','Unconscious, possible code','ems','critical',true,false),
  ('UNCON2','Unconscious, ALS2','ems','critical',true,false),
  ('ANMLBITE2','Animal bite, ALS2','ems','high',true,false),
  ('ASSAULT2','Assault, ALS2','ems','high',true,false),
  ('BURN2','Burns, ALS2','ems','high',true,false),
  ('COLDM','Cold exposure, multiple patients','ems','high',true,false),
  ('CP2','Chest pain, ALS2','ems','high',true,false),
  ('DROWN1','Drowning, ALS1','ems','high',true,false),
  ('ELECTRO1','Electrocution, ALS1','ems','high',true,false),
  ('FALL2','Fall, ALS2','ems','high',true,false),
  ('FALLPOL2','Fall, police on scene, ALS2','ems','high',true,false),
  ('HEART2','Heart problems, ALS2','ems','high',true,false),
  ('HEATM','Heat exposure, multiple patients','ems','high',true,false),
  ('INJURED2','Injured person, ALS2','ems','high',true,false),
  ('OD2','Overdose, ALS2','ems','high',true,false),
  ('ODINT2','Overdose, intentional, ALS2','ems','high',true,false),
  ('ODPOL2','Overdose, police on scene, ALS2','ems','high',true,false),
  ('PICCYCLE1','Cyclist struck, ALS1','ems','high',true,false),
  ('PICPED1','Pedestrian struck, ALS1','ems','high',true,false),
  ('SEIZURE2','Seizure, ALS2','ems','high',true,false),
  ('SHOOTA1','Shooting','ems','high',true,false),
  ('SHOTPOL1','Shooting, police on scene, ALS1','ems','high',true,false),
  ('STAB1','Stabbing','ems','high',true,false),
  ('STABPOL1','Stabbing, police on scene, ALS1','ems','high',true,false),
  ('TB2','Trouble breathing, ALS2','ems','high',true,false),
  ('TBPOL2','Trouble breathing, police on scene, ALS2','ems','high',true,false),
  ('TRAUMPOL1','Trauma, police on scene, ALS1','ems','high',true,false),
  ('ABDPN1','Abdominal pain, ALS1','ems','normal',false,false),
  ('ALLERGIC1','Allergic reaction, ALS1','ems','normal',false,false),
  ('ANMLBITE1','Animal bite, ALS1','ems','normal',false,false),
  ('ASSAULT1','Assault, ALS1','ems','normal',false,false),
  ('ASSAULTM','Assault, multiple patients','ems','normal',false,false),
  ('BACKPN1','Back pain, ALS1','ems','normal',false,false),
  ('BURN1','Burns, ALS1','ems','normal',false,false),
  ('BURNFEI1','Burns, fire investigator, ALS1','ems','normal',false,false),
  ('BURNFEIB','Burns, fire investigator, BLS','ems','normal',false,false),
  ('CHOKING1','Choking, ALS1','ems','normal',false,false),
  ('COLD1','Cold exposure, ALS1','ems','normal',false,false),
  ('CP1','Chest pain, ALS1','ems','normal',false,false),
  ('DECLOC1','Decreased level of consciousness, ALS1','ems','normal',false,false),
  ('DIABEPOL1','Diabetic, police on scene, ALS1','ems','normal',false,false),
  ('DIABETIC1','Diabetic emergency, ALS1','ems','normal',false,false),
  ('ELECHAZ1','Electrical hazard, ALS1','ems','normal',false,false),
  ('ELEVTR1','Elevator entrapment, ALS1','ems','normal',false,false),
  ('FALL1','Fall, ALS1','ems','normal',false,false),
  ('FALLPOL1','Fall, police on scene, ALS1','ems','normal',false,false),
  ('HEART1','Heart problems, ALS1','ems','normal',false,false),
  ('HEAT1','Heat exposure, ALS1','ems','normal',false,false),
  ('HEMM1','Hemorrhage, ALS1','ems','normal',false,false),
  ('INJURED1','Injured person, ALS1','ems','normal',false,false),
  ('INTRF1','Interfacility transfer, ALS1','ems','normal',false,false),
  ('INTRF2','Interfacility transfer, ALS2','ems','normal',false,false),
  ('INTRFMP1','Interfacility transfer, manpower, ALS1','ems','normal',false,false),
  ('MO1','Medical, unknown problem, ALS1','ems','normal',false,false),
  ('MOPOL1','Medical, police on scene, ALS1','ems','normal',false,false),
  ('OB1','Obstetric emergency, ALS1','ems','normal',false,false),
  ('OD1','Overdose, ALS1','ems','normal',false,false),
  ('ODINT1','Overdose, intentional, ALS1','ems','normal',false,false),
  ('ODPOL1','Overdose, police on scene, ALS1','ems','normal',false,false),
  ('PANALS1','Psychiatric / behavioral, ALS1','ems','normal',false,false),
  ('PANALS2','Psychiatric / behavioral, ALS2','ems','normal',false,false),
  ('PANONLYALS','Psychiatric, single ALS evaluation','ems','normal',false,false),
  ('SEIZURE1','Seizure, ALS1','ems','normal',false,false),
  ('SICK1','Sick person, ALS1','ems','normal',false,false),
  ('STROKE1','Stroke, ALS1','ems','normal',false,false),
  ('TB1','Trouble breathing, ALS1','ems','normal',false,false),
  ('TRNSFRM1','Transformer fire, ALS1','ems','normal',false,false),
  ('WIRES1','Wires down, ALS1','ems','normal',false,false),
  ('ABDPNB','Abdominal pain, BLS','ems','low',false,false),
  ('ALLERGICB','Allergic reaction, BLS','ems','low',false,false),
  ('ALRMAMA','Automatic medical alarm','ems','low',false,false),
  ('ANMLBITEB','Animal bite, BLS','ems','low',false,false),
  ('ASSAULTB','Assault, BLS','ems','low',false,false),
  ('ASSAULTR','Assault, routine','ems','low',false,false),
  ('BURNB','Burns, BLS','ems','low',false,false),
  ('CHOKINGB','Choking, BLS','ems','low',false,false),
  ('COLDB','Cold exposure, BLS','ems','low',false,false),
  ('DROWNB','Drowning, BLS','ems','low',false,false),
  ('FALLB','Fall, BLS','ems','low',false,false),
  ('FALLPOLB','Fall, police on scene, BLS','ems','low',false,false),
  ('HEATB','Heat exposure, BLS','ems','low',false,false),
  ('HEMMB','Hemorrhage, BLS','ems','low',false,false),
  ('INJURDMPB','Injured person, manpower, BLS','ems','low',false,false),
  ('INJUREDB','Injured person, BLS','ems','low',false,false),
  ('INJUREDR','Injured person, routine','ems','low',false,false),
  ('INTRFB','Interfacility transfer, BLS','ems','low',false,false),
  ('INTRFMPB','Interfacility transfer, manpower, BLS','ems','low',false,false),
  ('INTRFR','Interfacility transfer, routine','ems','low',false,false),
  ('MOB','Medical, unknown problem, BLS','ems','low',false,false),
  ('MOPOLB','Medical, police on scene, BLS','ems','low',false,false),
  ('MOR','Medical, unknown problem, routine','ems','low',false,false),
  ('OBB','Obstetric emergency, BLS','ems','low',false,false),
  ('ODB','Overdose, BLS','ems','low',false,false),
  ('ODINTB','Overdose, intentional, BLS','ems','low',false,false),
  ('ODPOLB','Overdose, police on scene, BLS','ems','low',false,false),
  ('ONEDOWNB','Person down, BLS','ems','low',false,false),
  ('ONEDWN32B','Person down, BLS (32D)','ems','low',false,false),
  ('PANBLSR','Psychiatric / behavioral, BLS (routine)','ems','low',false,false),
  ('PANMIHR','Mental health, routine','ems','low',false,false),
  ('SEIZUREB','Seizure, BLS','ems','low',false,false),
  ('SHOTPOLB','Shooting, police on scene, BLS','ems','low',false,false),
  ('SICKB','Sick person, BLS','ems','low',false,false),
  ('SICKR','Sick person, routine','ems','low',false,false),
  ('STABPOLB','Stabbing, police on scene, BLS','ems','low',false,false),
  ('STROKEB','Stroke, BLS','ems','low',false,false),
  ('TBB','Trouble breathing, BLS','ems','low',false,false),
  ('TRAUMPOLB','Trauma, police on scene, BLS','ems','low',false,false),
  ('UNEMER','Unknown emergency','ems','low',false,false),
  ('GASMAJOR','Major natural gas leak','hazmat','critical',true,false),
  ('TANKLG','Large tank fire','hazmat','critical',true,false),
  ('ALRMCOM','Carbon monoxide alarm, multiple patients','hazmat','high',true,false),
  ('ELECODRM','Electrical odor, multiple patients','hazmat','high',true,false),
  ('FUELODORM','Fuel odor, multiple patients','hazmat','high',true,false),
  ('GASLEAKM','Natural gas leak, multiple patients','hazmat','high',true,false),
  ('INHALEM','Inhalation injury, multiple patients','hazmat','high',true,false),
  ('UNKODRM','Unknown odor, multiple patients','hazmat','high',true,false),
  ('BOMBT','Bomb threat','hazmat','normal',false,false),
  ('ELECODR','Electrical odor','hazmat','normal',false,false),
  ('ELECODRB','Electrical odor, BLS','hazmat','normal',false,false),
  ('ELECODRR','Electrical odor, routine','hazmat','normal',false,false),
  ('FUELODORB','Fuel odor, BLS','hazmat','normal',false,false),
  ('FUELODORI','Fuel odor, inside','hazmat','normal',false,false),
  ('FUELODORO','Fuel odor, outside','hazmat','normal',false,false),
  ('FUELSPIL','Fuel spill','hazmat','normal',false,false),
  ('FUELSPILB','Fuel spill, BLS','hazmat','normal',false,false),
  ('FUELSPILM','Fuel spill, multiple patients','hazmat','normal',false,false),
  ('FUELSPLH','Fuel spill, hazmat','hazmat','normal',false,false),
  ('FUELSPLLG','Fuel spill, large','hazmat','normal',false,false),
  ('GASLEAK','Natural gas leak','hazmat','normal',false,false),
  ('GASLEAKB','Natural gas leak, BLS','hazmat','normal',false,false),
  ('GASLEAKO','Natural gas leak, outside','hazmat','normal',false,false),
  ('GASLEAKOB','Natural gas leak, outside, BLS','hazmat','normal',false,false),
  ('GASLEAKOM','Natural gas leak, outside, multiple patients','hazmat','normal',false,false),
  ('GASODOR','Natural gas odor','hazmat','normal',false,false),
  ('GASODORB','Natural gas odor, BLS','hazmat','normal',false,false),
  ('GASODORI','Natural gas odor, inside','hazmat','normal',false,false),
  ('GASODORM','Natural gas odor, multiple patients','hazmat','normal',false,false),
  ('HAZE','Haze / smoke in the area','hazmat','normal',false,false),
  ('HMINC','Hazmat incident','hazmat','normal',false,false),
  ('HMINCCNMP','Hazmat incident, contained, multiple patients','hazmat','normal',false,false),
  ('HMINCCNTD','Hazmat incident, contained','hazmat','normal',false,false),
  ('HMINCMPD','Hazmat incident, multiple patients','hazmat','normal',false,false),
  ('HMINV','Hazmat investigation','hazmat','normal',false,false),
  ('HMINVEST','Hazmat investigation','hazmat','normal',false,false),
  ('HMSPILL','Hazmat spill','hazmat','normal',false,false),
  ('HMSPILS','Hazmat spill, small','hazmat','normal',false,false),
  ('HMSPLS','Hazmat spill, small','hazmat','normal',false,false),
  ('INHALE1','Inhalation injury, ALS1','hazmat','normal',false,false),
  ('INHALEB','Inhalation injury, BLS','hazmat','normal',false,false),
  ('INVESTEXH','Investigation, explosion, hazmat','hazmat','normal',false,false),
  ('INVESTEXP','Investigation, explosion','hazmat','normal',false,false),
  ('OUTFIRH','Outside fire, hazmat','hazmat','normal',false,false),
  ('SHORTH','Electrical short, hazmat','hazmat','normal',false,false),
  ('SPKGINV','Suspicious package investigation','hazmat','normal',false,false),
  ('TANKBLDG','Tank fire near building','hazmat','normal',false,false),
  ('TANKS','Tank fire, small','hazmat','normal',false,false),
  ('TANKSMB','Tank fire, small, BLS','hazmat','normal',false,false),
  ('TANKSMH','Tank fire, small, hazmat','hazmat','normal',false,false),
  ('TANKSMIB','Tank fire, small, inside, BLS','hazmat','normal',false,false),
  ('TANKSMM','Tank fire, small, multiple patients','hazmat','normal',false,false),
  ('TNKFROUT','Tank fire out','hazmat','normal',false,false),
  ('TNKFROUTB','Tank fire out, BLS','hazmat','normal',false,false),
  ('TNKFROUTM','Tank fire out, multiple patients','hazmat','normal',false,false),
  ('UNKODORR','Unknown odor, routine','hazmat','normal',false,false),
  ('UNKODRB','Unknown odor, BLS','hazmat','normal',false,false),
  ('ALRMCO','Carbon monoxide alarm','hazmat','low',false,false),
  ('FUELSPILR','Fuel spill, routine','hazmat','low',false,false),
  ('HMINVSTR','Hazmat investigation (routine)','hazmat','low',false,false),
  ('ORDNCNE','Ordnance found','hazmat','low',false,false),
  ('SUSPKG','Suspicious package','hazmat','low',false,false),
  ('ELECDSTRM','Electrical distribution problem, multiple patients','service','high',true,false),
  ('ELECHAZM','Electrical hazard, multiple patients','service','high',true,false),
  ('ELECSOLM','Electrical, solar, multiple patients','service','high',true,false),
  ('ELECUNDM','Electrical underground, multiple patients','service','high',true,false),
  ('LIGHNINGM','Lightning strike, multiple patients','service','high',true,false),
  ('TRNSFRMM','Transformer fire, multiple patients','service','high',true,false),
  ('WIRESM','Wires down, multiple patients','service','high',true,false),
  ('AIRINVSTR','Aircraft investigation (routine)','service','normal',false,false),
  ('ALRMAFAR','Automatic fire alarm (routine)','service','normal',false,false),
  ('CTRLBRN','Controlled burn','service','normal',false,false),
  ('CTRLBRNB','Controlled burn, BLS','service','normal',false,false),
  ('CTRLBRNM','Controlled burn, multiple patients','service','normal',false,false),
  ('DSASTRINC','Disaster incident','service','normal',false,false),
  ('DSASTRMED','Disaster, medical','service','normal',false,false),
  ('DSASTRUTL','Disaster, utility','service','normal',false,false),
  ('ELECDSTR','Electrical distribution problem','service','normal',false,false),
  ('ELECDSTRB','Electrical distribution problem, BLS','service','normal',false,false),
  ('ELECHAZ','Electrical hazard','service','normal',false,false),
  ('ELECHAZB','Electrical hazard, BLS','service','normal',false,false),
  ('ELECHAZSE','Electrical hazard, single engine','service','normal',false,false),
  ('ELECHZSEB','Electrical hazard, single engine, BLS','service','normal',false,false),
  ('ELECSOL','Electrical, solar','service','normal',false,false),
  ('ELECSOLB','Electrical, solar, BLS','service','normal',false,false),
  ('ELECUNDR','Electrical underground, routine','service','normal',false,false),
  ('ELECUNDRB','Electrical underground, routine, BLS','service','normal',false,false),
  ('ELEVSTFA','Elevator entrapment with fire alarm','service','normal',false,false),
  ('ELEVSTFR','Elevator entrapment, fire response','service','normal',false,false),
  ('ELEVSTFRB','Elevator entrapment, fire response, BLS','service','normal',false,false),
  ('ELEVSTFRM','Elevator entrapment, fire response, multiple patients','service','normal',false,false),
  ('INVEST','Investigation','service','normal',false,false),
  ('INVESTB','Investigation, BLS','service','normal',false,false),
  ('INVESTM','Investigation, multiple patients','service','normal',false,false),
  ('LIGHNINGB','Lightning strike, BLS','service','normal',false,false),
  ('LIGHTNGSE','Lightning strike, single engine','service','normal',false,false),
  ('LIGHTNING','Lightning strike','service','normal',false,false),
  ('SHORT','Electrical short','service','normal',false,false),
  ('SMOKEINV','Smoke investigation','service','normal',false,false),
  ('TRANSFORMR','Transformer fire (routine)','service','normal',false,false),
  ('TRNSFRMB','Transformer fire, BLS','service','normal',false,false),
  ('WIRES','Wires down','service','normal',false,false),
  ('WIRESB','Wires down, BLS','service','normal',false,false),
  ('AIRBORNR','Aircraft, airborne emergency (routine)','service','low',false,false),
  ('ALRMAFA','Automatic fire alarm','service','low',false,false),
  ('ALRMELEVR','Elevator alarm (routine)','service','low',false,false),
  ('ALRMHOMR','Home alarm (routine)','service','low',false,false),
  ('ALRMSER','Alarm service (routine)','service','low',false,false),
  ('BACKCNTRY','Backcountry search','service','low',false,false),
  ('CTRBLRNR','Controlled burn (routine)','service','low',false,false),
  ('DSASTRINF','Disaster, information','service','low',false,false),
  ('DSASTRREF','Disaster, refuge','service','low',false,false),
  ('DSASTRSC','Disaster, standby','service','low',false,false),
  ('ELEVTR','Elevator entrapment','service','low',false,false),
  ('ELEVTRB','Elevator entrapment, BLS','service','low',false,false),
  ('ELEVTRR','Elevator entrapment, routine','service','low',false,false),
  ('FALLR','Fall, lift assist (routine)','service','low',false,false),
  ('INVESTR','Investigation, routine','service','low',false,false),
  ('SVCANMLR','Service call, animal (routine)','service','low',false,false),
  ('SVCCALL','Service call','service','low',false,false),
  ('SVCCALLB','Service call, BLS','service','low',false,false),
  ('SVCCALR','Service call (routine)','service','low',false,false),
  ('SVCCWELF','Welfare check','service','low',false,false),
  ('SVCLIFT','Lift assist','service','low',false,false),
  ('SVCLOCKR','Lockout (routine)','service','low',false,false),
  ('SVCVEHLO','Vehicle lockout','service','low',false,false),
  ('SVCWTRR','Water problem (routine)','service','low',false,false),
  ('TRANSFRMR','Transformer fire (routine)','service','low',false,false),
  ('WIRESR','Wires down, routine','service','low',false,false)
ON CONFLICT (code) DO UPDATE SET description = EXCLUDED.description, category = EXCLUDED.category, severity = EXCLUDED.severity,
  alertable = EXCLUDED.alertable, is_upgrade = EXCLUDED.is_upgrade, updated_at = now();
