/**
 * Call-type rules: CAD call code -> category / severity / alertable.
 *
 * Sources, in order of precedence:
 *   1. MCFRS Response Plans, section 1 (dispatch priority + response plan per IncType):
 *      full assignments (FJ/FK/HMFULL/GASFULL/TRC), technical rescue (RES/TECHWTR),
 *      collision-with-entrapment (PA1, PA2, PHM, AUTOFREX) and ALS2 / duty-officer EMS plans are
 *      alertable; adaptive/single-engine/BLS/service plans are not.
 *   2. Codes observed on the live board by the sta03 monitor that section 1 does not list
 *      (Metro, box upgrades, UCODE, SHOOTA*, STAB*, PICTRAP2 ...), kept with their grading.
 *   3. Hand overrides where the plan alone is misleading (e.g. CHIMNEY gets a full assignment
 *      but is graded "high"; interfacility transfers never page).
 *
 * Grading question: "would an off-duty firefighter/paramedic with a full ALS kit in their car
 * make a difference in the next few minutes?" critical = yes, drop everything; high = serious,
 * page by default; normal/low = shown on the board, never paged.
 *
 * These are the DEFAULTS. The live source of truth is the `call_type_rules` table (seeded by
 * migrations and editable by admins through the API), so the station can retune without a
 * redeploy. Keep this file and the newest `services/api/migrations/*call_types*.sql` in sync
 * (rules-parity.test.ts enforces it). Regenerate from the response plans with
 * packages/feed/scripts (see docs/CALL_TYPES.md).
 */
import type { IncidentCategory, Severity } from './index';

export interface CallTypeRule {
  code: string;
  description: string;
  category: IncidentCategory;
  severity: Severity;
  alertable: boolean;
  /** True for codes that represent an upgrade of an existing incident (2nd alarm etc.). */
  upgrade?: boolean;
}

const r = (code: string, description: string, category: IncidentCategory, severity: Severity, alertable: boolean, upgrade = false): CallTypeRule => ({
  code, description, category, severity, alertable, ...(upgrade ? { upgrade: true } : {}),
});

export const DEFAULT_CALL_TYPE_RULES: CallTypeRule[] = [
  // ---- fire / critical ----
  r('2ND', 'Second alarm', 'fire', 'critical', true, true),
  r('3RD', 'Third alarm', 'fire', 'critical', true, true),
  r('4TH', 'Fourth alarm', 'fire', 'critical', true, true),
  r('AIRCRSHF', 'Aircraft crash with fire', 'fire', 'critical', true),
  r('AIRCRSHFW', 'Aircraft crash with fire, water', 'fire', 'critical', true),
  r('AIRFIREL', 'Aircraft fire, large', 'fire', 'critical', true),
  r('AIRFULLE', 'Aircraft emergency, full assignment', 'fire', 'critical', true),
  r('BLDGFIRE', 'Building fire', 'fire', 'critical', true),
  r('BLDGFIRET', 'Building fire, occupants trapped', 'fire', 'critical', true),
  r('BLDGFREX', 'Building fire with explosion', 'fire', 'critical', true),
  r('BLDGFREXH', 'Building fire with explosion, hazmat', 'fire', 'critical', true),
  r('BLDGFRH', 'Building fire, hazmat', 'fire', 'critical', true),
  r('BLDGFRHM', 'Building fire, hazmat', 'fire', 'critical', true),
  r('BLDGFRHMT', 'Building fire, hazmat, occupants trapped', 'fire', 'critical', true),
  r('BLDGFRHR', 'High-rise building fire', 'fire', 'critical', true),
  r('BLDGFRHRT', 'High-rise building fire, occupants trapped', 'fire', 'critical', true),
  r('BLDGFRSMT', 'Building fire, smoke showing, occupants trapped', 'fire', 'critical', true),
  r('BUILDING', 'Building fire', 'fire', 'critical', true),
  r('HOUSE', 'House fire', 'fire', 'critical', true),
  r('HOUSET', 'House fire, occupants trapped', 'fire', 'critical', true),
  r('MAFULL', 'Mutual aid full assignment', 'fire', 'critical', true, true),
  r('UBOX', 'Box alarm upgrade (working fire)', 'fire', 'critical', true, true),
  r('UBOXHR', 'High-rise box upgrade', 'fire', 'critical', true, true),
  r('UBOXW', 'Box upgrade, working fire', 'fire', 'critical', true, true),
  r('VEHFRBLH', 'Vehicle fire near building, hazmat', 'fire', 'critical', true),
  r('VEHFRTRAP', 'Vehicle fire with entrapment', 'fire', 'critical', true),
  // ---- fire / high ----
  r('AIRFIRES', 'Aircraft fire, small', 'fire', 'high', true),
  r('APLNCM', 'Appliance fire, multiple patients', 'fire', 'high', true),
  r('BLDGFIRS', 'Building fire, small', 'fire', 'high', true),
  r('BLDGFIRSM', 'Building fire, small, multiple patients', 'fire', 'high', true),
  r('BLDGFRSME', 'Building fire, smoke, electrical', 'fire', 'high', true),
  r('BOATFIREM', 'Boat fire, multiple patients', 'fire', 'high', true),
  r('BOATFROUM', 'Boat fire out, multiple patients', 'fire', 'high', true),
  r('BRUSHLG', 'Brush fire, large', 'fire', 'high', true),
  r('BRUSHLGB', 'Brush fire, large, BLS', 'fire', 'high', true),
  r('BRUSHLGM', 'Brush fire, large, multiple patients', 'fire', 'high', true),
  r('CHIMNEY', 'Chimney fire', 'fire', 'high', true),
  r('CHIMNEYS', 'Chimney fire, small', 'fire', 'high', true),
  r('DECKOVER', 'Vehicle fire under deck-over', 'fire', 'high', true),
  r('DECKOVH', 'Vehicle fire under deck-over, hazmat', 'fire', 'high', true),
  r('OUTFIREM', 'Outside fire, multiple patients', 'fire', 'high', true),
  r('VEHFIREM', 'Vehicle fire, multiple patients', 'fire', 'high', true),
  r('VEHFIRPRK', 'Vehicle fire in parking garage', 'fire', 'high', true),
  r('VEHFRBLDB', 'Vehicle fire near building, BLS', 'fire', 'high', true),
  r('VEHFRTRH', 'Vehicle fire, tractor-trailer, hazmat', 'fire', 'high', true),
  r('VFIRPRKH', 'Vehicle fire in parking garage, hazmat', 'fire', 'high', true),
  // ---- fire / normal ----
  r('APLNCADA', 'Appliance fire, adaptive', 'fire', 'normal', false),
  r('APLNCADAB', 'Appliance fire, adaptive, BLS', 'fire', 'normal', false),
  r('APLNCB', 'Appliance fire, BLS', 'fire', 'normal', false),
  r('APLNCH', 'Appliance fire, hazmat', 'fire', 'normal', false),
  r('APLNCSE', 'Appliance fire, single engine', 'fire', 'normal', false),
  r('APPLIANCE', 'Appliance fire', 'fire', 'normal', false),
  r('AUTO', 'Vehicle incident', 'fire', 'normal', false),
  r('BOATFIRE', 'Boat fire', 'fire', 'normal', false),
  r('BOATFIREB', 'Boat fire, BLS', 'fire', 'normal', false),
  r('BOATFROUB', 'Boat fire out, BLS', 'fire', 'normal', false),
  r('BOATFROUT', 'Boat fire out', 'fire', 'normal', false),
  r('BOGS', 'Bog fire', 'fire', 'normal', false),
  r('BOGSB', 'Bog fire, BLS', 'fire', 'normal', false),
  r('BOGSM', 'Bog fire, multiple patients', 'fire', 'normal', false),
  r('BRUSHS', 'Brush fire, small', 'fire', 'normal', false),
  r('BRUSHSMB', 'Brush fire, small, BLS', 'fire', 'normal', false),
  r('BRUSHSMI', 'Brush fire, small, inside', 'fire', 'normal', false),
  r('BRUSHSMM', 'Brush fire, small, multiple patients', 'fire', 'normal', false),
  r('BTFIREWTR', 'Boat fire on the water', 'fire', 'normal', false),
  r('FIREOUT', 'Fire out', 'fire', 'normal', false),
  r('FIREOUTH', 'Fire out, hazmat', 'fire', 'normal', false),
  r('ODORSMK', 'Odor of smoke', 'fire', 'normal', false),
  r('OUTFIRE', 'Outside fire', 'fire', 'normal', false),
  r('OUTFIREB', 'Outside fire, BLS', 'fire', 'normal', false),
  r('OUTFRADA', 'Outside fire, adaptive', 'fire', 'normal', false),
  r('OUTFRADAB', 'Outside fire, adaptive, BLS', 'fire', 'normal', false),
  r('VEHEXP', 'Vehicle explosion', 'fire', 'normal', false),
  r('VEHEXPH', 'Vehicle explosion, hazmat', 'fire', 'normal', false),
  r('VEHFIRE', 'Vehicle fire', 'fire', 'normal', false),
  r('VEHFIREB', 'Vehicle fire, BLS', 'fire', 'normal', false),
  r('VEHFIRH', 'Vehicle fire, hazmat', 'fire', 'normal', false),
  r('VEHFIRLG', 'Vehicle fire, large', 'fire', 'normal', false),
  r('VEHFIRLGB', 'Vehicle fire, large, BLS', 'fire', 'normal', false),
  r('VEHFRBLDG', 'Vehicle fire near building', 'fire', 'normal', false),
  r('VEHFREXP', 'Vehicle fire with explosion', 'fire', 'normal', false),
  r('VEHFRLGH', 'Vehicle fire, large, hazmat', 'fire', 'normal', false),
  // ---- fire / low ----
  r('APLNCSER', 'Appliance fire, single engine, routine', 'fire', 'low', false),
  r('OUTFIRER', 'Outside fire, routine', 'fire', 'low', false),
  // ---- rescue / critical ----
  r('AIRCRSHP', 'Aircraft crash', 'rescue', 'critical', true),
  r('AIRCRSHPW', 'Aircraft crash in water', 'rescue', 'critical', true),
  r('DSASTRTRP', 'Disaster, people trapped', 'rescue', 'critical', true),
  r('ENTRAP1', 'Entrapment, ALS1', 'rescue', 'critical', true),
  r('ENTRAP2', 'Entrapment, ALS2', 'rescue', 'critical', true),
  r('ENTRAPHM1', 'Entrapment with hazmat, ALS1', 'rescue', 'critical', true),
  r('ENTRAPHM2', 'Entrapment with hazmat, ALS2', 'rescue', 'critical', true),
  r('FLDVEHT', 'Vehicle in flood water, occupants trapped', 'rescue', 'critical', true),
  r('METCRSH', 'Metro crash', 'rescue', 'critical', true),
  r('METRO', 'Metro rail incident', 'rescue', 'critical', true),
  r('METRORESQP', 'Metro rescue, person', 'rescue', 'critical', true),
  r('PIC1TRAP', 'Collision with entrapment', 'rescue', 'critical', true),
  r('PICMULT1', 'Multi-vehicle collision, ALS1', 'rescue', 'critical', true),
  r('PICMULT2', 'Multi-vehicle collision, ALS2', 'rescue', 'critical', true),
  r('PICTRAP1', 'Collision with entrapment, ALS1', 'rescue', 'critical', true),
  r('PICTRAP2', 'Collision with entrapment, ALS2', 'rescue', 'critical', true),
  r('PICTRAPF2', 'Collision with entrapment and fire, ALS2', 'rescue', 'critical', true),
  r('PICTRFHM2', 'Collision, entrapment, fire and hazmat, ALS2', 'rescue', 'critical', true),
  r('PICTRFM2', 'Collision with entrapment and fire, ALS2', 'rescue', 'critical', true),
  r('PICTRPHM1', 'Collision with entrapment, hazmat, ALS1', 'rescue', 'critical', true),
  r('PICTRPHM2', 'Collision with entrapment, hazmat, ALS2', 'rescue', 'critical', true),
  r('TRAINCRSH', 'Train crash', 'rescue', 'critical', true),
  r('TRAINFIRE', 'Train fire', 'rescue', 'critical', true),
  r('TRAINPED', 'Train vs pedestrian', 'rescue', 'critical', true),
  r('TRTCOLAPS', 'Structural collapse', 'rescue', 'critical', true),
  r('TRTCOLAPW', 'Collapse with water rescue', 'rescue', 'critical', true),
  r('TRTCONFIN', 'Confined space rescue', 'rescue', 'critical', true),
  r('TRTTECH', 'Technical rescue', 'rescue', 'critical', true),
  r('TRTTECHW', 'Technical rescue with water resources', 'rescue', 'critical', true),
  r('TRTTRENCH', 'Trench rescue', 'rescue', 'critical', true),
  // ---- rescue / high ----
  r('DSASTRDAN', 'Disaster, danger', 'rescue', 'high', true),
  r('ELEVTRTRP', 'Elevator entrapment with injury', 'rescue', 'high', true),
  r('PIC2', 'Collision with injuries, ALS2', 'rescue', 'high', true),
  r('PICEXB', 'Collision, extrication needed, BLS', 'rescue', 'high', true),
  r('PICHM2', 'Collision with hazmat, ALS2', 'rescue', 'high', true),
  // ---- rescue / normal ----
  r('AIRALERT', 'Aircraft alert', 'rescue', 'normal', false),
  r('AIRMINRE', 'Aircraft minor emergency', 'rescue', 'normal', false),
  r('PIC1', 'Collision with injuries, ALS1', 'rescue', 'normal', false),
  r('PICB', 'Collision with injuries, BLS', 'rescue', 'normal', false),
  r('PICHM1', 'Collision with hazmat, ALS1', 'rescue', 'normal', false),
  r('PICHMB', 'Collision with hazmat, BLS', 'rescue', 'normal', false),
  r('TRAININV', 'Train investigation', 'rescue', 'normal', false),
  r('TRAININVR', 'Train investigation (routine)', 'rescue', 'normal', false),
  // ---- rescue / low ----
  r('LOSTPERR', 'Lost person (routine)', 'rescue', 'low', false),
  // ---- ems / critical ----
  r('ALLERGIC2', 'Allergic reaction, ALS2', 'ems', 'critical', true),
  r('BURNADA2', 'Burns, ALS2 with fire response', 'ems', 'critical', true),
  r('BURNMPD2', 'Burns, multiple patients', 'ems', 'critical', true),
  r('CHOKING2', 'Choking, ALS2', 'ems', 'critical', true),
  r('CPR2', 'Cardiac arrest', 'ems', 'critical', true),
  r('CPRDROWN2', 'Cardiac arrest, drowning', 'ems', 'critical', true),
  r('CPRHEMM2', 'Cardiac arrest, hemorrhage', 'ems', 'critical', true),
  r('CPRHM2', 'Cardiac arrest, hazmat', 'ems', 'critical', true),
  r('CPROD2', 'Cardiac arrest, overdose', 'ems', 'critical', true),
  r('CPRSHOT2', 'Cardiac arrest, gunshot', 'ems', 'critical', true),
  r('CPRSTAB2', 'Cardiac arrest, stabbing', 'ems', 'critical', true),
  r('CPRTRAUM2', 'Cardiac arrest, trauma', 'ems', 'critical', true),
  r('DROWN2', 'Drowning, ALS2', 'ems', 'critical', true),
  r('DSASTRMCI', 'Disaster, mass casualty', 'ems', 'critical', true),
  r('ELECTRO2', 'Electrocution, ALS2', 'ems', 'critical', true),
  r('ELECTROM', 'Electrocution, multiple patients', 'ems', 'critical', true),
  r('HEMM2', 'Hemorrhage, ALS2', 'ems', 'critical', true),
  r('SHOOTA2', 'Shooting, ALS2', 'ems', 'critical', true),
  r('SHOTPOL2', 'Shooting, police on scene, ALS2', 'ems', 'critical', true),
  r('SHOTPOLM', 'Shooting, police on scene, multiple patients', 'ems', 'critical', true),
  r('STAB2', 'Stabbing, ALS2', 'ems', 'critical', true),
  r('STABPOL2', 'Stabbing, police on scene, ALS2', 'ems', 'critical', true),
  r('STABPOLM', 'Stabbing, police on scene, multiple patients', 'ems', 'critical', true),
  r('TRAUMPOL2', 'Trauma, police on scene, ALS2', 'ems', 'critical', true),
  r('TRAUMPOLM', 'Trauma, police on scene, multiple patients', 'ems', 'critical', true),
  r('UCODE', 'Unconscious, possible code', 'ems', 'critical', true),
  r('UNCON2', 'Unconscious, ALS2', 'ems', 'critical', true),
  // ---- ems / high ----
  r('ANMLBITE2', 'Animal bite, ALS2', 'ems', 'high', true),
  r('ASSAULT2', 'Assault, ALS2', 'ems', 'high', true),
  r('BURN2', 'Burns, ALS2', 'ems', 'high', true),
  r('COLDM', 'Cold exposure, multiple patients', 'ems', 'high', true),
  r('CP2', 'Chest pain, ALS2', 'ems', 'high', true),
  r('DROWN1', 'Drowning, ALS1', 'ems', 'high', true),
  r('ELECTRO1', 'Electrocution, ALS1', 'ems', 'high', true),
  r('FALL2', 'Fall, ALS2', 'ems', 'high', true),
  r('FALLPOL2', 'Fall, police on scene, ALS2', 'ems', 'high', true),
  r('HEART2', 'Heart problems, ALS2', 'ems', 'high', true),
  r('HEATM', 'Heat exposure, multiple patients', 'ems', 'high', true),
  r('INJURED2', 'Injured person, ALS2', 'ems', 'high', true),
  r('OD2', 'Overdose, ALS2', 'ems', 'high', true),
  r('ODINT2', 'Overdose, intentional, ALS2', 'ems', 'high', true),
  r('ODPOL2', 'Overdose, police on scene, ALS2', 'ems', 'high', true),
  r('PICCYCLE1', 'Cyclist struck, ALS1', 'ems', 'high', true),
  r('PICPED1', 'Pedestrian struck, ALS1', 'ems', 'high', true),
  r('SEIZURE2', 'Seizure, ALS2', 'ems', 'high', true),
  r('SHOOTA1', 'Shooting', 'ems', 'high', true),
  r('SHOTPOL1', 'Shooting, police on scene, ALS1', 'ems', 'high', true),
  r('STAB1', 'Stabbing', 'ems', 'high', true),
  r('STABPOL1', 'Stabbing, police on scene, ALS1', 'ems', 'high', true),
  r('TB2', 'Trouble breathing, ALS2', 'ems', 'high', true),
  r('TBPOL2', 'Trouble breathing, police on scene, ALS2', 'ems', 'high', true),
  r('TRAUMPOL1', 'Trauma, police on scene, ALS1', 'ems', 'high', true),
  // ---- ems / normal ----
  r('ABDPN1', 'Abdominal pain, ALS1', 'ems', 'normal', false),
  r('ALLERGIC1', 'Allergic reaction, ALS1', 'ems', 'normal', false),
  r('ANMLBITE1', 'Animal bite, ALS1', 'ems', 'normal', false),
  r('ASSAULT1', 'Assault, ALS1', 'ems', 'normal', false),
  r('ASSAULTM', 'Assault, multiple patients', 'ems', 'normal', false),
  r('BACKPN1', 'Back pain, ALS1', 'ems', 'normal', false),
  r('BURN1', 'Burns, ALS1', 'ems', 'normal', false),
  r('BURNFEI1', 'Burns, fire investigator, ALS1', 'ems', 'normal', false),
  r('BURNFEIB', 'Burns, fire investigator, BLS', 'ems', 'normal', false),
  r('CHOKING1', 'Choking, ALS1', 'ems', 'normal', false),
  r('COLD1', 'Cold exposure, ALS1', 'ems', 'normal', false),
  r('CP1', 'Chest pain, ALS1', 'ems', 'normal', false),
  r('DECLOC1', 'Decreased level of consciousness, ALS1', 'ems', 'normal', false),
  r('DIABEPOL1', 'Diabetic, police on scene, ALS1', 'ems', 'normal', false),
  r('DIABETIC1', 'Diabetic emergency, ALS1', 'ems', 'normal', false),
  r('ELECHAZ1', 'Electrical hazard, ALS1', 'ems', 'normal', false),
  r('ELEVTR1', 'Elevator entrapment, ALS1', 'ems', 'normal', false),
  r('FALL1', 'Fall, ALS1', 'ems', 'normal', false),
  r('FALLPOL1', 'Fall, police on scene, ALS1', 'ems', 'normal', false),
  r('HEART1', 'Heart problems, ALS1', 'ems', 'normal', false),
  r('HEAT1', 'Heat exposure, ALS1', 'ems', 'normal', false),
  r('HEMM1', 'Hemorrhage, ALS1', 'ems', 'normal', false),
  r('INJURED1', 'Injured person, ALS1', 'ems', 'normal', false),
  r('INTRF1', 'Interfacility transfer, ALS1', 'ems', 'normal', false),
  r('INTRF2', 'Interfacility transfer, ALS2', 'ems', 'normal', false),
  r('INTRFMP1', 'Interfacility transfer, manpower, ALS1', 'ems', 'normal', false),
  r('MO1', 'Medical, unknown problem, ALS1', 'ems', 'normal', false),
  r('MOPOL1', 'Medical, police on scene, ALS1', 'ems', 'normal', false),
  r('OB1', 'Obstetric emergency, ALS1', 'ems', 'normal', false),
  r('OD1', 'Overdose, ALS1', 'ems', 'normal', false),
  r('ODINT1', 'Overdose, intentional, ALS1', 'ems', 'normal', false),
  r('ODPOL1', 'Overdose, police on scene, ALS1', 'ems', 'normal', false),
  r('PANALS1', 'Psychiatric / behavioral, ALS1', 'ems', 'normal', false),
  r('PANALS2', 'Psychiatric / behavioral, ALS2', 'ems', 'normal', false),
  r('PANONLYALS', 'Psychiatric, single ALS evaluation', 'ems', 'normal', false),
  r('SEIZURE1', 'Seizure, ALS1', 'ems', 'normal', false),
  r('SICK1', 'Sick person, ALS1', 'ems', 'normal', false),
  r('STROKE1', 'Stroke, ALS1', 'ems', 'normal', false),
  r('TB1', 'Trouble breathing, ALS1', 'ems', 'normal', false),
  r('TRNSFRM1', 'Transformer fire, ALS1', 'ems', 'normal', false),
  r('WIRES1', 'Wires down, ALS1', 'ems', 'normal', false),
  // ---- ems / low ----
  r('ABDPNB', 'Abdominal pain, BLS', 'ems', 'low', false),
  r('ALLERGICB', 'Allergic reaction, BLS', 'ems', 'low', false),
  r('ALRMAMA', 'Automatic medical alarm', 'ems', 'low', false),
  r('ANMLBITEB', 'Animal bite, BLS', 'ems', 'low', false),
  r('ASSAULTB', 'Assault, BLS', 'ems', 'low', false),
  r('ASSAULTR', 'Assault, routine', 'ems', 'low', false),
  r('BURNB', 'Burns, BLS', 'ems', 'low', false),
  r('CHOKINGB', 'Choking, BLS', 'ems', 'low', false),
  r('COLDB', 'Cold exposure, BLS', 'ems', 'low', false),
  r('DROWNB', 'Drowning, BLS', 'ems', 'low', false),
  r('FALLB', 'Fall, BLS', 'ems', 'low', false),
  r('FALLPOLB', 'Fall, police on scene, BLS', 'ems', 'low', false),
  r('HEATB', 'Heat exposure, BLS', 'ems', 'low', false),
  r('HEMMB', 'Hemorrhage, BLS', 'ems', 'low', false),
  r('INJURDMPB', 'Injured person, manpower, BLS', 'ems', 'low', false),
  r('INJUREDB', 'Injured person, BLS', 'ems', 'low', false),
  r('INJUREDR', 'Injured person, routine', 'ems', 'low', false),
  r('INTRFB', 'Interfacility transfer, BLS', 'ems', 'low', false),
  r('INTRFMPB', 'Interfacility transfer, manpower, BLS', 'ems', 'low', false),
  r('INTRFR', 'Interfacility transfer, routine', 'ems', 'low', false),
  r('MOB', 'Medical, unknown problem, BLS', 'ems', 'low', false),
  r('MOPOLB', 'Medical, police on scene, BLS', 'ems', 'low', false),
  r('MOR', 'Medical, unknown problem, routine', 'ems', 'low', false),
  r('OBB', 'Obstetric emergency, BLS', 'ems', 'low', false),
  r('ODB', 'Overdose, BLS', 'ems', 'low', false),
  r('ODINTB', 'Overdose, intentional, BLS', 'ems', 'low', false),
  r('ODPOLB', 'Overdose, police on scene, BLS', 'ems', 'low', false),
  r('ONEDOWNB', 'Person down, BLS', 'ems', 'low', false),
  r('ONEDWN32B', 'Person down, BLS (32D)', 'ems', 'low', false),
  r('PANBLSR', 'Psychiatric / behavioral, BLS (routine)', 'ems', 'low', false),
  r('PANMIHR', 'Mental health, routine', 'ems', 'low', false),
  r('SEIZUREB', 'Seizure, BLS', 'ems', 'low', false),
  r('SHOTPOLB', 'Shooting, police on scene, BLS', 'ems', 'low', false),
  r('SICKB', 'Sick person, BLS', 'ems', 'low', false),
  r('SICKR', 'Sick person, routine', 'ems', 'low', false),
  r('STABPOLB', 'Stabbing, police on scene, BLS', 'ems', 'low', false),
  r('STROKEB', 'Stroke, BLS', 'ems', 'low', false),
  r('TBB', 'Trouble breathing, BLS', 'ems', 'low', false),
  r('TRAUMPOLB', 'Trauma, police on scene, BLS', 'ems', 'low', false),
  r('UNEMER', 'Unknown emergency', 'ems', 'low', false),
  // ---- hazmat / critical ----
  r('GASMAJOR', 'Major natural gas leak', 'hazmat', 'critical', true),
  r('TANKLG', 'Large tank fire', 'hazmat', 'critical', true),
  // ---- hazmat / high ----
  r('ALRMCOM', 'Carbon monoxide alarm, multiple patients', 'hazmat', 'high', true),
  r('ELECODRM', 'Electrical odor, multiple patients', 'hazmat', 'high', true),
  r('FUELODORM', 'Fuel odor, multiple patients', 'hazmat', 'high', true),
  r('GASLEAKM', 'Natural gas leak, multiple patients', 'hazmat', 'high', true),
  r('INHALEM', 'Inhalation injury, multiple patients', 'hazmat', 'high', true),
  r('UNKODRM', 'Unknown odor, multiple patients', 'hazmat', 'high', true),
  // ---- hazmat / normal ----
  r('BOMBT', 'Bomb threat', 'hazmat', 'normal', false),
  r('ELECODR', 'Electrical odor', 'hazmat', 'normal', false),
  r('ELECODRB', 'Electrical odor, BLS', 'hazmat', 'normal', false),
  r('ELECODRR', 'Electrical odor, routine', 'hazmat', 'normal', false),
  r('FUELODORB', 'Fuel odor, BLS', 'hazmat', 'normal', false),
  r('FUELODORI', 'Fuel odor, inside', 'hazmat', 'normal', false),
  r('FUELODORO', 'Fuel odor, outside', 'hazmat', 'normal', false),
  r('FUELSPIL', 'Fuel spill', 'hazmat', 'normal', false),
  r('FUELSPILB', 'Fuel spill, BLS', 'hazmat', 'normal', false),
  r('FUELSPILM', 'Fuel spill, multiple patients', 'hazmat', 'normal', false),
  r('FUELSPLH', 'Fuel spill, hazmat', 'hazmat', 'normal', false),
  r('FUELSPLLG', 'Fuel spill, large', 'hazmat', 'normal', false),
  r('GASLEAK', 'Natural gas leak', 'hazmat', 'normal', false),
  r('GASLEAKB', 'Natural gas leak, BLS', 'hazmat', 'normal', false),
  r('GASLEAKO', 'Natural gas leak, outside', 'hazmat', 'normal', false),
  r('GASLEAKOB', 'Natural gas leak, outside, BLS', 'hazmat', 'normal', false),
  r('GASLEAKOM', 'Natural gas leak, outside, multiple patients', 'hazmat', 'normal', false),
  r('GASODOR', 'Natural gas odor', 'hazmat', 'normal', false),
  r('GASODORB', 'Natural gas odor, BLS', 'hazmat', 'normal', false),
  r('GASODORI', 'Natural gas odor, inside', 'hazmat', 'normal', false),
  r('GASODORM', 'Natural gas odor, multiple patients', 'hazmat', 'normal', false),
  r('HAZE', 'Haze / smoke in the area', 'hazmat', 'normal', false),
  r('HMINC', 'Hazmat incident', 'hazmat', 'normal', false),
  r('HMINCCNMP', 'Hazmat incident, contained, multiple patients', 'hazmat', 'normal', false),
  r('HMINCCNTD', 'Hazmat incident, contained', 'hazmat', 'normal', false),
  r('HMINCMPD', 'Hazmat incident, multiple patients', 'hazmat', 'normal', false),
  r('HMINV', 'Hazmat investigation', 'hazmat', 'normal', false),
  r('HMINVEST', 'Hazmat investigation', 'hazmat', 'normal', false),
  r('HMSPILL', 'Hazmat spill', 'hazmat', 'normal', false),
  r('HMSPILS', 'Hazmat spill, small', 'hazmat', 'normal', false),
  r('HMSPLS', 'Hazmat spill, small', 'hazmat', 'normal', false),
  r('INHALE1', 'Inhalation injury, ALS1', 'hazmat', 'normal', false),
  r('INHALEB', 'Inhalation injury, BLS', 'hazmat', 'normal', false),
  r('INVESTEXH', 'Investigation, explosion, hazmat', 'hazmat', 'normal', false),
  r('INVESTEXP', 'Investigation, explosion', 'hazmat', 'normal', false),
  r('OUTFIRH', 'Outside fire, hazmat', 'hazmat', 'normal', false),
  r('SHORTH', 'Electrical short, hazmat', 'hazmat', 'normal', false),
  r('SPKGINV', 'Suspicious package investigation', 'hazmat', 'normal', false),
  r('TANKBLDG', 'Tank fire near building', 'hazmat', 'normal', false),
  r('TANKS', 'Tank fire, small', 'hazmat', 'normal', false),
  r('TANKSMB', 'Tank fire, small, BLS', 'hazmat', 'normal', false),
  r('TANKSMH', 'Tank fire, small, hazmat', 'hazmat', 'normal', false),
  r('TANKSMIB', 'Tank fire, small, inside, BLS', 'hazmat', 'normal', false),
  r('TANKSMM', 'Tank fire, small, multiple patients', 'hazmat', 'normal', false),
  r('TNKFROUT', 'Tank fire out', 'hazmat', 'normal', false),
  r('TNKFROUTB', 'Tank fire out, BLS', 'hazmat', 'normal', false),
  r('TNKFROUTM', 'Tank fire out, multiple patients', 'hazmat', 'normal', false),
  r('UNKODORR', 'Unknown odor, routine', 'hazmat', 'normal', false),
  r('UNKODRB', 'Unknown odor, BLS', 'hazmat', 'normal', false),
  // ---- hazmat / low ----
  r('ALRMCO', 'Carbon monoxide alarm', 'hazmat', 'low', false),
  r('FUELSPILR', 'Fuel spill, routine', 'hazmat', 'low', false),
  r('HMINVSTR', 'Hazmat investigation (routine)', 'hazmat', 'low', false),
  r('ORDNCNE', 'Ordnance found', 'hazmat', 'low', false),
  r('SUSPKG', 'Suspicious package', 'hazmat', 'low', false),
  // ---- service / high ----
  r('ELECDSTRM', 'Electrical distribution problem, multiple patients', 'service', 'high', true),
  r('ELECHAZM', 'Electrical hazard, multiple patients', 'service', 'high', true),
  r('ELECSOLM', 'Electrical, solar, multiple patients', 'service', 'high', true),
  r('ELECUNDM', 'Electrical underground, multiple patients', 'service', 'high', true),
  r('LIGHNINGM', 'Lightning strike, multiple patients', 'service', 'high', true),
  r('TRNSFRMM', 'Transformer fire, multiple patients', 'service', 'high', true),
  r('WIRESM', 'Wires down, multiple patients', 'service', 'high', true),
  // ---- service / normal ----
  r('AIRINVSTR', 'Aircraft investigation (routine)', 'service', 'normal', false),
  r('ALRMAFAR', 'Automatic fire alarm (routine)', 'service', 'normal', false),
  r('CTRLBRN', 'Controlled burn', 'service', 'normal', false),
  r('CTRLBRNB', 'Controlled burn, BLS', 'service', 'normal', false),
  r('CTRLBRNM', 'Controlled burn, multiple patients', 'service', 'normal', false),
  r('DSASTRINC', 'Disaster incident', 'service', 'normal', false),
  r('DSASTRMED', 'Disaster, medical', 'service', 'normal', false),
  r('DSASTRUTL', 'Disaster, utility', 'service', 'normal', false),
  r('ELECDSTR', 'Electrical distribution problem', 'service', 'normal', false),
  r('ELECDSTRB', 'Electrical distribution problem, BLS', 'service', 'normal', false),
  r('ELECHAZ', 'Electrical hazard', 'service', 'normal', false),
  r('ELECHAZB', 'Electrical hazard, BLS', 'service', 'normal', false),
  r('ELECHAZSE', 'Electrical hazard, single engine', 'service', 'normal', false),
  r('ELECHZSEB', 'Electrical hazard, single engine, BLS', 'service', 'normal', false),
  r('ELECSOL', 'Electrical, solar', 'service', 'normal', false),
  r('ELECSOLB', 'Electrical, solar, BLS', 'service', 'normal', false),
  r('ELECUNDR', 'Electrical underground, routine', 'service', 'normal', false),
  r('ELECUNDRB', 'Electrical underground, routine, BLS', 'service', 'normal', false),
  r('ELEVSTFA', 'Elevator entrapment with fire alarm', 'service', 'normal', false),
  r('ELEVSTFR', 'Elevator entrapment, fire response', 'service', 'normal', false),
  r('ELEVSTFRB', 'Elevator entrapment, fire response, BLS', 'service', 'normal', false),
  r('ELEVSTFRM', 'Elevator entrapment, fire response, multiple patients', 'service', 'normal', false),
  r('INVEST', 'Investigation', 'service', 'normal', false),
  r('INVESTB', 'Investigation, BLS', 'service', 'normal', false),
  r('INVESTM', 'Investigation, multiple patients', 'service', 'normal', false),
  r('LIGHNINGB', 'Lightning strike, BLS', 'service', 'normal', false),
  r('LIGHTNGSE', 'Lightning strike, single engine', 'service', 'normal', false),
  r('LIGHTNING', 'Lightning strike', 'service', 'normal', false),
  r('SHORT', 'Electrical short', 'service', 'normal', false),
  r('SMOKEINV', 'Smoke investigation', 'service', 'normal', false),
  r('TRANSFORMR', 'Transformer fire (routine)', 'service', 'normal', false),
  r('TRNSFRMB', 'Transformer fire, BLS', 'service', 'normal', false),
  r('WIRES', 'Wires down', 'service', 'normal', false),
  r('WIRESB', 'Wires down, BLS', 'service', 'normal', false),
  // ---- service / low ----
  r('AIRBORNR', 'Aircraft, airborne emergency (routine)', 'service', 'low', false),
  r('ALRMAFA', 'Automatic fire alarm', 'service', 'low', false),
  r('ALRMELEVR', 'Elevator alarm (routine)', 'service', 'low', false),
  r('ALRMHOMR', 'Home alarm (routine)', 'service', 'low', false),
  r('ALRMSER', 'Alarm service (routine)', 'service', 'low', false),
  r('BACKCNTRY', 'Backcountry search', 'service', 'low', false),
  r('CTRBLRNR', 'Controlled burn (routine)', 'service', 'low', false),
  r('DSASTRINF', 'Disaster, information', 'service', 'low', false),
  r('DSASTRREF', 'Disaster, refuge', 'service', 'low', false),
  r('DSASTRSC', 'Disaster, standby', 'service', 'low', false),
  r('ELEVTR', 'Elevator entrapment', 'service', 'low', false),
  r('ELEVTRB', 'Elevator entrapment, BLS', 'service', 'low', false),
  r('ELEVTRR', 'Elevator entrapment, routine', 'service', 'low', false),
  r('FALLR', 'Fall, lift assist (routine)', 'service', 'low', false),
  r('INVESTR', 'Investigation, routine', 'service', 'low', false),
  r('SVCANMLR', 'Service call, animal (routine)', 'service', 'low', false),
  r('SVCCALL', 'Service call', 'service', 'low', false),
  r('SVCCALLB', 'Service call, BLS', 'service', 'low', false),
  r('SVCCALR', 'Service call (routine)', 'service', 'low', false),
  r('SVCCWELF', 'Welfare check', 'service', 'low', false),
  r('SVCLIFT', 'Lift assist', 'service', 'low', false),
  r('SVCLOCKR', 'Lockout (routine)', 'service', 'low', false),
  r('SVCVEHLO', 'Vehicle lockout', 'service', 'low', false),
  r('SVCWTRR', 'Water problem (routine)', 'service', 'low', false),
  r('TRANSFRMR', 'Transformer fire (routine)', 'service', 'low', false),
  r('WIRESR', 'Wires down, routine', 'service', 'low', false),
];

/**
 * Classify a code that has no explicit rule. Conservative: unknown codes are
 * shown on the board but never page anyone.
 */
export function classifyUnknownCode(code: string): Omit<CallTypeRule, 'code' | 'description'> {
  const c = code.toUpperCase();
  let category: IncidentCategory = 'other';
  if (/HAZ|GAS|CO\b|CARBON|SPILL|CHEM/.test(c)) category = 'hazmat';
  else if (/FIRE|BLDG|HOUSE|SMOKE|ALARM|BRUSH|VEHF|APT/.test(c)) category = 'fire';
  else if (/PIC|TRAP|RESQ|COLAP|WATER|TRT|TRAIN|METRO|AIR|ELEV/.test(c)) category = 'rescue';
  else if (/\d$|CPR|MED|SICK|CHEST|STROKE|SEIZ|DIAB|OB\b|PREG|PSYCH|UNCON|BLEED|TB\b|ABD|BACK|HEAD/.test(c)) category = 'ems';
  else if (/SERV|ASSIST|LOCK|INVEST|PUBLIC|WIRES|TREE/.test(c)) category = 'service';
  return { category, severity: 'normal', alertable: false };
}

export const CALL_TYPE_RULES_BY_CODE: ReadonlyMap<string, CallTypeRule> = new Map(
  DEFAULT_CALL_TYPE_RULES.map((r) => [r.code, r]),
);

/** MCFRS box prefix (first-due station) -> city used for geocoding/display. From sta03 runcard_config. */
export const STATION_CITY: Record<string, string> = {
  '01': 'SILVER SPRING', '02': 'TAKOMA PARK', '03': 'ROCKVILLE', '04': 'SANDY SPRING', '05': 'KENSINGTON',
  '06': 'BETHESDA', '07': 'CHEVY CHASE', '08': 'GAITHERSBURG', '09': 'CLARKSBURG', '10': 'BETHESDA',
  '11': 'BETHESDA', '12': 'SILVER SPRING', '13': 'DAMASCUS', '14': 'BEALLSVILLE', '15': 'BURTONSVILLE',
  '16': 'SILVER SPRING', '17': 'LAYTONSVILLE', '18': 'SILVER SPRING', '19': 'SILVER SPRING', '20': 'BETHESDA',
  '21': 'SILVER SPRING', '22': 'GERMANTOWN', '23': 'ROCKVILLE', '24': 'SILVER SPRING', '25': 'SILVER SPRING',
  '26': 'BETHESDA', '27': 'GAITHERSBURG', '28': 'DERWOOD', '29': 'GERMANTOWN', '30': 'POTOMAC',
  '31': 'DARNESTOWN', '32': 'ROCKVILLE', '33': 'POTOMAC', '34': 'GERMANTOWN', '35': 'CLARKSBURG',
  '40': 'OLNEY', '50': 'BETHESDA', '51': 'BETHESDA', '52': 'POTOMAC', '53': 'GAITHERSBURG',
};

/** Box-specific overrides where the station prefix is misleading (from sta03). */
export const BOX_CITY_OVERRIDES: Record<string, string> = {
  '2514': 'ROCKVILLE',
  '2520': 'ASPEN HILL',
  '0807': 'WASHINGTON GROVE',
};

/** MCFRS battalion groupings (from sta03 funcs.is_same_battalion). */
export const STATION_BATTALION: Record<string, string> = Object.fromEntries(
  Object.entries({
    '1': ['01', '02', '12', '15', '16', '19', '24'],
    '2': ['06', '07', '10', '11', '20', '26', '30'],
    '3': ['03', '08', '23', '31', '33', '28', '32'],
    '4': ['04', '05', '18', '21', '25', '40'],
    '5': ['09', '13', '14', '17', '22', '29', '34', '35'],
  }).flatMap(([batt, stations]) => stations.map((s) => [s, batt] as const)),
);

export function cityForBox(box: string | null): string | null {
  if (!box) return null;
  return BOX_CITY_OVERRIDES[box] ?? STATION_CITY[box.slice(0, 2)] ?? null;
}
